name: petcorner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0     # For making API calls to your Flask backend
  shared_preferences: ^2.2.0  # To store login session
  cupertino_icons: ^1.0.8
  flutter_image_slideshow: ^0.1.3
  flutter_animate: ^4.2.0
  image_picker: ^1.0.4 
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.8.3
  intl: ^0.18.0 


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  
  assets:
    - lib/assets/images/

   

